import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { Container } from '@/shared/ui'
import { Header } from '@/widgets'

const dmSans = DM_Sans({
	variable: '--font-main',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={dmSans.className}>
				<Container>
					<Header />
					{children}
				</Container>
			</body>
		</html>
	)
}
